### PR TITLE
fix deconstruction of push and replace

### LINKED ISSUE #34: TypeError: Cannot read property '_setCurrentUrl' of undefined
deconstructing `push` and `replace` breaks the memory router

the following code works for next but not for the memory router:

```tsx
const  {push} = useRouter();
push("/");
```

pushError

### PR DESCRIPTION
**Pull request by jantimon**
this pr fixes #34

### CODE REVIEW

File: src/MemoryRouter.tsx [hunk 1]
```diff
@@ -106,6 +106,9 @@ export class MemoryRouter extends BaseRouter {
     super();
     if (initialUrl) this.setCurrentUrl(initialUrl);
     if (async) this.async = async;
+    this.push = this.push.bind(this);
+    this.replace = this.replace.bind(this);
+    this.setCurrentUrl = this.setCurrentUrl.bind(this);
```
Comment (scottrippey) [inline src/MemoryRouter.tsx:111]: I'd prefer to use fat-arrow syntax when defining these methods?

**Review by scottrippey — CHANGES_REQUESTED** [review]

**Review by scottrippey — APPROVED** [review]

**Comment by scottrippey** [comment]
Published as `0.6.5`
